// `.env.json` is generated by the `npm run build` command
//import env from './.env.json';

export const environment = {
  production: true,
  version: '1.0.0',
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
